import { RunDetail } from "./types";

export const SAMPLE_RUN_CLASSIFICATION: RunDetail = {
  id: "run-9a8b7c6d-5e4f-4321-8899-aabbccddeeff",
  status: "done",
  task_type: "classification",
  target_column: "target",
  dataset_name: "iris_multivariate_drift.csv",
  rows_count: 150,
  columns_count: 5,
  config_hash: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce",
  dataset_hash: "a467b610d32152fb22af1831ef8e543666d9b9a67a0ae6525fa501e40eb42ec2",
  git_sha: "1b2b42c",
  created_at: "2026-08-28T23:14:10Z",
  updated_at: "2026-08-28T23:14:48Z",
  duration_seconds: 38.4,
  config: {
    task_type: "classification",
    target_column: "target",
    imputation_method: "mice",
    outlier_method: "isolation_forest",
    seed: 42,
    n_trials: 20,
    cv_folds: 5,
    stacking_cv_folds: 5,
  },
  gates: [
    {
      gate_name: "MaxNullRateGate",
      passed: true,
      score: 0.02,
      threshold: 0.20,
      details: "Maximum missing rate per feature is 2.0% (threshold: 20.0%)",
      columns_flagged: [],
    },
    {
      gate_name: "SchemaConformanceGate",
      passed: true,
      score: 1.0,
      threshold: 1.0,
      details: "All 5 expected features verified with conformant dtypes (float64, int64)",
      columns_flagged: [],
    },
    {
      gate_name: "DriftGate (PSI & KS)",
      passed: true,
      score: 0.042,
      threshold: 0.10,
      details: "Population Stability Index = 0.042 (stable, < 0.10 drift cutoff)",
      columns_flagged: [],
    },
  ],
  rl_result: {
    meta_features: {
      missing_rate: 0.02,
      skewness: 0.38,
      cardinality_mean: 35.2,
      class_imbalance_ratio: 1.0,
      drift_score: 0.042,
    },
    state_bin: [0, 1, 2, 0, 0],
    action_chosen: {
      imputation: "mice",
      outlier: "isolation_forest",
      threshold: 0.05,
    },
    delta_reward: 0.041,
    baseline_metric: 0.942,
    optimized_metric: 0.983,
    convergence_history: [
      { episode: 1, reward: 0.012, epsilon: 0.90 },
      { episode: 2, reward: 0.018, epsilon: 0.81 },
      { episode: 3, reward: 0.026, epsilon: 0.72 },
      { episode: 4, reward: 0.035, epsilon: 0.65 },
      { episode: 5, reward: 0.038, epsilon: 0.58 },
      { episode: 6, reward: 0.041, epsilon: 0.52 },
      { episode: 7, reward: 0.041, epsilon: 0.47 },
      { episode: 8, reward: 0.041, epsilon: 0.42 },
    ],
  },
  optuna_trials: [
    { trial_number: 1, family: "random_forest", score: 0.966, duration_seconds: 0.8, params: { n_estimators: 100, max_depth: 4 }, state: "COMPLETE" },
    { trial_number: 2, family: "xgboost", score: 0.973, duration_seconds: 1.1, params: { learning_rate: 0.05, max_depth: 3, n_estimators: 120 }, state: "COMPLETE" },
    { trial_number: 3, family: "lightgbm", score: 0.960, duration_seconds: 0.9, params: { learning_rate: 0.08, num_leaves: 15 }, state: "COMPLETE" },
    { trial_number: 4, family: "linear", score: 0.947, duration_seconds: 0.3, params: { C: 1.2, penalty: "l2" }, state: "COMPLETE" },
    { trial_number: 5, family: "xgboost", score: 0.980, duration_seconds: 1.2, params: { learning_rate: 0.03, max_depth: 4, n_estimators: 150 }, state: "COMPLETE" },
    { trial_number: 6, family: "random_forest", score: 0.973, duration_seconds: 0.8, params: { n_estimators: 180, max_depth: 5 }, state: "COMPLETE" },
  ],
  family_best_models: [
    { family: "xgboost", best_score: 0.980, n_trials_evaluated: 6, best_params: { learning_rate: 0.03, max_depth: 4, n_estimators: 150 } },
    { family: "random_forest", best_score: 0.973, n_trials_evaluated: 5, best_params: { n_estimators: 180, max_depth: 5 } },
    { family: "lightgbm", best_score: 0.960, n_trials_evaluated: 5, best_params: { learning_rate: 0.08, num_leaves: 15 } },
    { family: "linear", best_score: 0.947, n_trials_evaluated: 4, best_params: { C: 1.2, penalty: "l2" } },
  ],
  stacking_result: {
    task_type: "classification",
    ensemble_score: 0.9867,
    base_family_weights: {
      xgboost: 0.48,
      random_forest: 0.32,
      lightgbm: 0.14,
      linear: 0.06,
    },
    meta_learner_type: "LogisticRegression (L2 regularized)",
    metric_name: "Multiclass ROC-AUC / Macro F1",
    metrics: {
      accuracy_or_r2: 0.9867,
      f1_or_rmse: 0.9866,
      roc_auc_or_mae: 0.9980,
    },
  },
  maml_timeline: [
    {
      batch_id: 1,
      drift_detected: false,
      drift_psi: 0.024,
      adapted: false,
      inner_gradient_steps: 0,
      pre_adaptation_score: 0.980,
      post_adaptation_score: 0.980,
      selected_feature_count: 4,
      timestamp: "23:14:20",
    },
    {
      batch_id: 2,
      drift_detected: true,
      drift_psi: 0.142,
      adapted: true,
      inner_gradient_steps: 3,
      pre_adaptation_score: 0.892,
      post_adaptation_score: 0.974,
      selected_feature_count: 4,
      timestamp: "23:14:32",
    },
    {
      batch_id: 3,
      drift_detected: false,
      drift_psi: 0.038,
      adapted: false,
      inner_gradient_steps: 0,
      pre_adaptation_score: 0.974,
      post_adaptation_score: 0.974,
      selected_feature_count: 4,
      timestamp: "23:14:44",
    },
  ],
  bounded_summary: {
    summary_text: "DataPrepX automated pipeline evaluated 4 model families following MICE imputation and Isolation Forest outlier filtering. Stacking ensemble achieved 98.67% F1 score, outperforming the single best tuned base estimator (XGBoost @ 98.00%) with statistically verified confidence.",
    generated_at: "2026-08-28T23:14:48Z",
    model_name: "ollama:qwen2.5-coder:1.5b (bounded determinism)",
    grounding_stats: {
      raw_rows: 150,
      imputed_missing_pct: 2.0,
      outlier_dropped_or_flagged_pct: 3.3,
      base_best_f1: 0.9800,
      stacking_f1: 0.9867,
      relative_lift_pct: 0.68,
    },
    claims: [
      {
        id: "c1",
        text: "MICE imputation and Isolation Forest preprocessing improved downstream cross-validated score from baseline 0.942 to 0.983.",
        verifiable_metric: "delta_reward",
        computed_value: "+0.041",
        confidence_level: "HIGH",
        confidence_score: 0.96,
        p_value_or_ci: "p < 0.001 (5-fold CV)",
        verification_passed: true,
      },
      {
        id: "c2",
        text: "Optuna Bayesian hyperparameter search converged in 6 iterations for XGBoost with optimal learning rate 0.03 and max depth 4.",
        verifiable_metric: "optuna_xgboost_score",
        computed_value: "0.9800",
        confidence_level: "HIGH",
        confidence_score: 0.98,
        p_value_or_ci: "variance < 0.004",
        verification_passed: true,
      },
      {
        id: "c3",
        text: "Stacked ensemble meta-learner assigns 48% weight to XGBoost and 32% to Random Forest, achieving final F1 score of 0.9867.",
        verifiable_metric: "ensemble_score",
        computed_value: "0.9867",
        confidence_level: "HIGH",
        confidence_score: 0.94,
        p_value_or_ci: "95% CI [0.978, 0.995]",
        verification_passed: true,
      },
      {
        id: "c4",
        text: "MAML fast-adaptation restored accuracy from 89.2% to 97.4% within 3 gradient steps following concept drift detection in batch 2.",
        verifiable_metric: "maml_adapted_score",
        computed_value: "0.9740",
        confidence_level: "MODERATE",
        confidence_score: 0.86,
        p_value_or_ci: "3-step inner loop",
        verification_passed: true,
      },
    ],
  },
  lineage: {
    run_id: "run-9a8b7c6d-5e4f-4321-8899-aabbccddeeff",
    git_sha: "1b2b42c",
    dataset_id: "ds-a467b610d32152fb22af1831ef8e543666d9b9a6",
    nodes: [
      {
        id: "node-dataset",
        label: "Dataset Ingestion",
        type: "dataset",
        content_hash: "a467b610d32152fb22af1831ef8e543666d9b9a67a0ae6525fa501e40eb42ec2",
        status: "completed",
        timestamp: "23:14:10",
        metadata: { rows: 150, cols: 5, filename: "iris_multivariate_drift.csv" },
      },
      {
        id: "node-gates",
        label: "Validation Gates (Null & Drift)",
        type: "gate",
        content_hash: "g81f9a2c3d4e5f67a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1",
        status: "completed",
        timestamp: "23:14:14",
        metadata: { passed_all: true, null_rate: "2.0%", psi_drift: "0.042" },
      },
      {
        id: "node-impute",
        label: "MICE Imputation",
        type: "transformation",
        content_hash: "t1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
        status: "completed",
        timestamp: "23:14:18",
        metadata: { method: "MICE", max_iter: 10, imputed_cells: 15 },
      },
      {
        id: "node-outliers",
        label: "Isolation Forest Filter",
        type: "transformation",
        content_hash: "t9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8",
        status: "completed",
        timestamp: "23:14:22",
        metadata: { method: "IsolationForest", contamination: 0.05, outliers_flagged: 5 },
      },
      {
        id: "node-rl",
        label: "RL Q-Learning Policy",
        type: "rl_policy",
        content_hash: "r4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3",
        status: "completed",
        timestamp: "23:14:25",
        metadata: { state_bin: [0, 1, 2, 0, 0], delta_reward: "+0.041", q_value: 0.884 },
      },
      {
        id: "node-optuna",
        label: "Bayesian HPO (4 Families)",
        type: "hpo_trial",
        content_hash: "o7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6",
        status: "completed",
        timestamp: "23:14:38",
        metadata: { total_trials: 20, best_family: "xgboost", best_cv: 0.980 },
      },
      {
        id: "node-ensemble",
        label: "Stacked Ensemble Model",
        type: "ensemble",
        content_hash: "e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4",
        status: "completed",
        timestamp: "23:14:44",
        metadata: { ensemble_f1: 0.9867, meta_learner: "LogisticRegression", git_sha: "1b2b42c" },
      },
      {
        id: "node-summary",
        label: "Bounded LLM Summary",
        type: "summary",
        content_hash: "s3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2",
        status: "completed",
        timestamp: "23:14:48",
        metadata: { verified_claims: 4, failed_claims: 0, model: "qwen2.5-coder:1.5b" },
      },
    ],
    edges: [
      { from: "node-dataset", to: "node-gates" },
      { from: "node-gates", to: "node-impute" },
      { from: "node-impute", to: "node-outliers" },
      { from: "node-outliers", to: "node-rl" },
      { from: "node-rl", to: "node-optuna" },
      { from: "node-optuna", to: "node-ensemble" },
      { from: "node-ensemble", to: "node-summary" },
    ],
  },
};

export const SAMPLE_RUN_REGRESSION: RunDetail = {
  id: "run-3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f",
  status: "done",
  task_type: "regression",
  target_column: "MedHouseVal",
  dataset_name: "california_housing_sample.csv",
  rows_count: 500,
  columns_count: 8,
  config_hash: "9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e",
  dataset_hash: "e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4",
  git_sha: "1b2b42c",
  created_at: "2026-08-28T21:05:00Z",
  updated_at: "2026-08-28T21:06:12Z",
  duration_seconds: 72.1,
  config: {
    task_type: "regression",
    target_column: "MedHouseVal",
    imputation_method: "knn",
    outlier_method: "lof",
    seed: 123,
    n_trials: 30,
    cv_folds: 5,
    stacking_cv_folds: 5,
  },
  gates: [
    {
      gate_name: "MaxNullRateGate",
      passed: true,
      score: 0.015,
      threshold: 0.20,
      details: "Maximum null rate across features is 1.5%",
    },
    {
      gate_name: "SchemaConformanceGate",
      passed: true,
      score: 1.0,
      threshold: 1.0,
      details: "8 numeric features conform to float64 schema",
    },
    {
      gate_name: "DriftGate (KS Test)",
      passed: true,
      score: 0.031,
      threshold: 0.05,
      details: "Kolmogorov-Smirnov distance = 0.031 (< 0.05 cutoff)",
    },
  ],
  rl_result: {
    meta_features: {
      missing_rate: 0.015,
      skewness: 0.82,
      cardinality_mean: 140.5,
      class_imbalance_ratio: 1.0,
      drift_score: 0.031,
    },
    state_bin: [0, 2, 3, 0, 0],
    action_chosen: {
      imputation: "knn",
      outlier: "lof",
      threshold: 0.05,
    },
    delta_reward: 0.068,
    baseline_metric: 0.724,
    optimized_metric: 0.842,
    convergence_history: [
      { episode: 1, reward: 0.020, epsilon: 0.90 },
      { episode: 2, reward: 0.035, epsilon: 0.81 },
      { episode: 3, reward: 0.050, epsilon: 0.72 },
      { episode: 4, reward: 0.062, epsilon: 0.65 },
      { episode: 5, reward: 0.068, epsilon: 0.58 },
    ],
  },
  optuna_trials: [
    { trial_number: 1, family: "lightgbm", score: 0.831, duration_seconds: 1.4, params: { learning_rate: 0.05, num_leaves: 31 }, state: "COMPLETE" },
    { trial_number: 2, family: "xgboost", score: 0.839, duration_seconds: 2.1, params: { learning_rate: 0.04, max_depth: 6 }, state: "COMPLETE" },
    { trial_number: 3, family: "random_forest", score: 0.812, duration_seconds: 1.8, params: { n_estimators: 200, max_depth: 10 }, state: "COMPLETE" },
    { trial_number: 4, family: "linear", score: 0.641, duration_seconds: 0.2, params: { alpha: 0.5, l1_ratio: 0.5 }, state: "COMPLETE" },
  ],
  family_best_models: [
    { family: "xgboost", best_score: 0.839, n_trials_evaluated: 10, best_params: { learning_rate: 0.04, max_depth: 6 } },
    { family: "lightgbm", best_score: 0.831, n_trials_evaluated: 10, best_params: { learning_rate: 0.05, num_leaves: 31 } },
    { family: "random_forest", best_score: 0.812, n_trials_evaluated: 8, best_params: { n_estimators: 200, max_depth: 10 } },
    { family: "linear", best_score: 0.641, n_trials_evaluated: 2, best_params: { alpha: 0.5, l1_ratio: 0.5 } },
  ],
  stacking_result: {
    task_type: "regression",
    ensemble_score: 0.854,
    base_family_weights: {
      xgboost: 0.54,
      lightgbm: 0.36,
      random_forest: 0.08,
      linear: 0.02,
    },
    meta_learner_type: "Ridge Regression (CV-tuned alpha)",
    metric_name: "R² Coefficient of Determination",
    metrics: {
      accuracy_or_r2: 0.854,
      f1_or_rmse: 0.482,
      roc_auc_or_mae: 0.312,
    },
  },
  maml_timeline: [],
  bounded_summary: {
    summary_text: "Regression pipeline tuned 4 base model families. Stacked Ridge ensemble achieved R² = 0.854 (RMSE = 0.482), surpassing single XGBoost model (R² = 0.839) with deterministic verification.",
    generated_at: "2026-08-28T21:06:12Z",
    model_name: "ollama:qwen2.5-coder:1.5b (bounded determinism)",
    grounding_stats: {
      raw_rows: 500,
      imputed_missing_pct: 1.5,
      outlier_dropped_or_flagged_pct: 5.0,
      base_best_r2: 0.839,
      stacking_r2: 0.854,
    },
    claims: [
      {
        id: "reg-c1",
        text: "KNN imputation + LOF outlier filtering increased validation R² from 0.724 to 0.842.",
        verifiable_metric: "delta_reward",
        computed_value: "+0.068",
        confidence_level: "HIGH",
        confidence_score: 0.95,
        verification_passed: true,
      },
      {
        id: "reg-c2",
        text: "Stacked ensemble meta-learner achieved R² of 0.854 with 54% weight on XGBoost and 36% on LightGBM.",
        verifiable_metric: "ensemble_score",
        computed_value: "0.854",
        confidence_level: "HIGH",
        confidence_score: 0.92,
        verification_passed: true,
      },
    ],
  },
  lineage: {
    run_id: "run-3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f",
    git_sha: "1b2b42c",
    dataset_id: "ds-e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8",
    nodes: [
      {
        id: "node-dataset",
        label: "Dataset Ingestion",
        type: "dataset",
        content_hash: "e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4",
        status: "completed",
        timestamp: "21:05:00",
        metadata: { rows: 500, cols: 8, filename: "california_housing_sample.csv" },
      },
      {
        id: "node-gates",
        label: "Validation Gates (Null & KS)",
        type: "gate",
        content_hash: "g123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
        status: "completed",
        timestamp: "21:05:05",
        metadata: { passed_all: true },
      },
      {
        id: "node-impute",
        label: "KNN Imputation",
        type: "transformation",
        content_hash: "t123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
        status: "completed",
        timestamp: "21:05:12",
        metadata: { method: "KNN", n_neighbors: 5 },
      },
      {
        id: "node-outliers",
        label: "Local Outlier Factor (LOF)",
        type: "transformation",
        content_hash: "t23456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0",
        status: "completed",
        timestamp: "21:05:20",
        metadata: { method: "LOF", contamination: 0.05 },
      },
      {
        id: "node-ensemble",
        label: "Stacked Regression Model",
        type: "ensemble",
        content_hash: "e3456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01",
        status: "completed",
        timestamp: "21:06:05",
        metadata: { r2_score: 0.854, rmse: 0.482 },
      },
    ],
    edges: [
      { from: "node-dataset", to: "node-gates" },
      { from: "node-gates", to: "node-impute" },
      { from: "node-impute", to: "node-outliers" },
      { from: "node-outliers", to: "node-ensemble" },
    ],
  },
};
